### ISSUE TITLE
Allow `whodunnit` column name to be configurable

### ISSUE THREAD

**Issue by chrisdpeters** [liveeditor/draftsman#31]
While it's a cute name from the paper_trail project, it's also super annoying. :)

**Comment by jakehockey10** [comment]
Is this only intended to store a name of who did it?  I'm looking at how the `whodunnit` of draft records could point to the user that initiated the `draft_creation`.  The method `current_user` does work, but since the `whodunnit` column is a string, I just get something like `#<User:0x007f51605ca860>`.  Would you recommend changing the column type?  Or would you recommend me retrofitting the column as is, override the `user_for_draftsman` method to make it return some sort of string identifier to the user, then let my app decipher the whodunnit column on read?

**Comment by defbyte** [comment]
as far as I know this is intended to capture the name (or any other data) about the current user.

I believe this was mired after the paper_trail gem.

You could setup your own method to create the string you need.

**Comment by chrisdpeters** [comment]
@jakehockey10 @defbyte In paper_trail, I believe the examples record names of people for `whodunnit`, which I think is lame.

I tend to change `whodunnit` to an integer and store the user's ID so I can join it if need be. I'd much prefer that the column were named `user_id`, which is why I opened this issue to have the option of overriding it.
