### ISSUE TITLE
SerializedAttributes is deprecated in Rails 4.2.x, and will be removed in Rails 5

### ISSUE THREAD

**Issue by dpaluy** [liveeditor/draftsman#33]
I'm working with Rails 4.2 and I'm getting the following warning:

```
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will
be removed in Rails 5.0.
```

This issue is similar to https://github.com/airblade/paper_trail/issues/416

I added the following patch (to suppress deprecation warnings) https://github.com/dpaluy/draftsman/blob/afce35b3985c79760176f31710c11a77b1201f0e/config/initializers/draftsman.rb

**Comment by chrisdpeters** [comment]
@dpaluy Thank you for reporting this.

I noticed in your fork that you moved this over to an initializer instead of `spec/support`. Can you help me understand why? I'm not seeing this deprecation notice in my dev logs in the app that's using this gem, but obviously it is being spit out all over the place when running tests.

**Comment by dpaluy** [comment]
@chrisdpeters I saw those warning in my main Rails app (4.2.4), thus I moved it to an initializer.
